### ISSUE TITLE
Windows path error

### ISSUE THREAD

**Issue by bengeendokter** [linus/testy#7]
When running tests on my Windows PC I get the following error
 
 ```
 AssertionError: expected Error: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
 ...
 at Context.<anonymous> (.../testy/src/index.js:33:40)
 ```

This seems to be a windows only problem because running tests on my Linux machine works fine.

I tried to look up some documentation on [Node URL](https://nodejs.org/api/url.html#new-urlinput-base) and I don't know if this is the right solution but changing [line 106 in src/lib.js](https://github.com/linus/testy/blob/25915f05f889e2b583b0bbe002653678f838330c/src/lib.js#L106) from
```
 const path = `${directory}/${filename}`
```
to
 ```
const path = new URL(
`${directory}/${filename}`.replaceAll("\\", "/"),
"file:"
).pathname;
```
seems to fix the problem. Also thank you for creating this tool. I loved doctest in Python and it is great to have a similar tool for JavaScript 🙂

**Comment by linus** [comment]
Thanks @bengeendokter for the issue. If you have the opportunity, please try the fix in #9 and verify that it fixes the issue for you.

**Comment by bengeendokter** [comment]
Hello @linus , I tried your fix but I 'm afraid it doesn't seem to fix the problem. I still get the same error:
![console error](https://user-images.githubusercontent.com/45427540/208402160-610c30c0-4743-403d-b173-efd15518061f.gif)

**Comment by linus** [comment]
Thanks @bengeendokter -- that was helpful, and not at all the error I expected! Providing a full file: URL is probably a good idea in any case. Could I bother you to try the PR once more (I have updated it)? I don't have a Windows environment easily at hand.

**Comment by bengeendokter** [comment]
@linus I tried running it with the new commits but it still throws the same error after [importing the context at line 131](https://github.com/linus/testy/blob/1b06a90de655ca4b67e144ba08168a40a70f8069/src/lib.js#L131)

**Comment by linus** [comment]
Hi again @bengeendokter -- I'm sorry about the delay, but I decided to get a Windows install and test it out myself. I think I have a workable solution now. Tested with node LTS (18.x) on Windows 10. Please try it out in #9  and let me know.

Happy new year! 🎆 🎊 🍾

**Comment by bengeendokter** [comment]
Hi @linus, it works great on my Windows PC. I don't get any errors and the tests run fine! Thank you for providing a fix and happy new year for you too! 🙂🎉

**Comment by linus** [comment]
Nice @bengeendokter! Please keep using it and report back with any issues/suggestions. I plan to release 1.2.0 soon-ish, with the Windows support and a few improvements to error handling (especially if the code under test throws/rejects unexpectedly) and performance. 🥂
